/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Kullanicilar.Admin;
import Kullanicilar.Kullanici;
import Kullanicilar.Ogrenci;
import Kullanicilar.Ogretmen;
import Kullanicilar.OkulMuduru;

/**
 *
 * @author Elif Eftelya
 */
public class OBSUI extends javax.swing.JFrame {

    Admin admin;
    Ogrenci ogrenci;
    Ogretmen ogretmen;
    OkulMuduru okulMuduru;

    /**
     * Creates new form OBSUI
     */
    public OBSUI() {
        initComponents();
    }

    public OBSUI(Kullanici kullanici) {
        initComponents();

        switch (kullanici.getRole()) {
            case "Admin" -> admin = (Admin) kullanici;
            case "Ogrenci" -> ogrenci = (Ogrenci) kullanici;
            case "Ogretmen" -> ogretmen = (Ogretmen) kullanici;
            case "OkulMuduru" -> okulMuduru = (OkulMuduru) kullanici;
            default -> kullanici = null;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_AnaPanel = new javax.swing.JPanel();
        jPanel_MenuBar = new javax.swing.JPanel();
        jToggleButton_Okul = new javax.swing.JToggleButton();
        jToggleButton_Ogretmen = new javax.swing.JToggleButton();
        jToggleButton_Sinif = new javax.swing.JToggleButton();
        jToggleButton_Sinav = new javax.swing.JToggleButton();
        jToggleButton_Kullanici = new javax.swing.JToggleButton();
        jPanel_Header2 = new javax.swing.JPanel();
        jPanel_Footer = new javax.swing.JPanel();
        jPanel_CardBody = new javax.swing.JPanel();
        jPanel_Kullanici = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_Okul = new javax.swing.JPanel();
        jPanel_Ogretmen = new javax.swing.JPanel();
        jPanel_Sinif = new javax.swing.JPanel();
        jPanel_Sinav = new javax.swing.JPanel();
        jPanel_Header1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_MenuBar.setBackground(new java.awt.Color(188, 189, 220));

        jToggleButton_Okul.setText("jToggleButton2");

        jToggleButton_Ogretmen.setText("jToggleButton3");

        jToggleButton_Sinif.setText("jToggleButton4");

        jToggleButton_Sinav.setText("jToggleButton5");

        jToggleButton_Kullanici.setText("jToggleButton1");

        javax.swing.GroupLayout jPanel_MenuBarLayout = new javax.swing.GroupLayout(jPanel_MenuBar);
        jPanel_MenuBar.setLayout(jPanel_MenuBarLayout);
        jPanel_MenuBarLayout.setHorizontalGroup(
            jPanel_MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_MenuBarLayout.createSequentialGroup()
                        .addGroup(jPanel_MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton_Okul, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton_Ogretmen, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton_Sinif, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton_Sinav, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jToggleButton_Kullanici, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_MenuBarLayout.setVerticalGroup(
            jPanel_MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuBarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jToggleButton_Kullanici, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton_Okul, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton_Ogretmen, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton_Sinif, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton_Sinav, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Header2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel_Header2Layout = new javax.swing.GroupLayout(jPanel_Header2);
        jPanel_Header2.setLayout(jPanel_Header2Layout);
        jPanel_Header2Layout.setHorizontalGroup(
            jPanel_Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_Header2Layout.setVerticalGroup(
            jPanel_Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel_Footer.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel_FooterLayout = new javax.swing.GroupLayout(jPanel_Footer);
        jPanel_Footer.setLayout(jPanel_FooterLayout);
        jPanel_FooterLayout.setHorizontalGroup(
            jPanel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_FooterLayout.setVerticalGroup(
            jPanel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jPanel_CardBody.setBackground(new java.awt.Color(218, 218, 235));
        jPanel_CardBody.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(239, 237, 245));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(252, 251, 253));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_KullaniciLayout = new javax.swing.GroupLayout(jPanel_Kullanici);
        jPanel_Kullanici.setLayout(jPanel_KullaniciLayout);
        jPanel_KullaniciLayout.setHorizontalGroup(
            jPanel_KullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_KullaniciLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_KullaniciLayout.setVerticalGroup(
            jPanel_KullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_CardBody.add(jPanel_Kullanici, "card2");

        javax.swing.GroupLayout jPanel_OkulLayout = new javax.swing.GroupLayout(jPanel_Okul);
        jPanel_Okul.setLayout(jPanel_OkulLayout);
        jPanel_OkulLayout.setHorizontalGroup(
            jPanel_OkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        jPanel_OkulLayout.setVerticalGroup(
            jPanel_OkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jPanel_CardBody.add(jPanel_Okul, "card3");

        javax.swing.GroupLayout jPanel_OgretmenLayout = new javax.swing.GroupLayout(jPanel_Ogretmen);
        jPanel_Ogretmen.setLayout(jPanel_OgretmenLayout);
        jPanel_OgretmenLayout.setHorizontalGroup(
            jPanel_OgretmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        jPanel_OgretmenLayout.setVerticalGroup(
            jPanel_OgretmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jPanel_CardBody.add(jPanel_Ogretmen, "card4");

        javax.swing.GroupLayout jPanel_SinifLayout = new javax.swing.GroupLayout(jPanel_Sinif);
        jPanel_Sinif.setLayout(jPanel_SinifLayout);
        jPanel_SinifLayout.setHorizontalGroup(
            jPanel_SinifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        jPanel_SinifLayout.setVerticalGroup(
            jPanel_SinifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jPanel_CardBody.add(jPanel_Sinif, "card5");

        javax.swing.GroupLayout jPanel_SinavLayout = new javax.swing.GroupLayout(jPanel_Sinav);
        jPanel_Sinav.setLayout(jPanel_SinavLayout);
        jPanel_SinavLayout.setHorizontalGroup(
            jPanel_SinavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        jPanel_SinavLayout.setVerticalGroup(
            jPanel_SinavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jPanel_CardBody.add(jPanel_Sinav, "card6");

        jPanel_Header1.setBackground(new java.awt.Color(75, 0, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Okul Bilgi Sistemi");

        javax.swing.GroupLayout jPanel_Header1Layout = new javax.swing.GroupLayout(jPanel_Header1);
        jPanel_Header1.setLayout(jPanel_Header1Layout);
        jPanel_Header1Layout.setHorizontalGroup(
            jPanel_Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Header1Layout.setVerticalGroup(
            jPanel_Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_AnaPanelLayout = new javax.swing.GroupLayout(jPanel_AnaPanel);
        jPanel_AnaPanel.setLayout(jPanel_AnaPanelLayout);
        jPanel_AnaPanelLayout.setHorizontalGroup(
            jPanel_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_AnaPanelLayout.createSequentialGroup()
                .addComponent(jPanel_MenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Header2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_CardBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel_AnaPanelLayout.setVerticalGroup(
            jPanel_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AnaPanelLayout.createSequentialGroup()
                .addComponent(jPanel_Header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AnaPanelLayout.createSequentialGroup()
                        .addComponent(jPanel_Header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel_CardBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel_Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_MenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OBSUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OBSUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OBSUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OBSUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OBSUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_AnaPanel;
    private javax.swing.JPanel jPanel_CardBody;
    private javax.swing.JPanel jPanel_Footer;
    private javax.swing.JPanel jPanel_Header1;
    private javax.swing.JPanel jPanel_Header2;
    private javax.swing.JPanel jPanel_Kullanici;
    private javax.swing.JPanel jPanel_MenuBar;
    private javax.swing.JPanel jPanel_Ogretmen;
    private javax.swing.JPanel jPanel_Okul;
    private javax.swing.JPanel jPanel_Sinav;
    private javax.swing.JPanel jPanel_Sinif;
    private javax.swing.JToggleButton jToggleButton_Kullanici;
    private javax.swing.JToggleButton jToggleButton_Ogretmen;
    private javax.swing.JToggleButton jToggleButton_Okul;
    private javax.swing.JToggleButton jToggleButton_Sinav;
    private javax.swing.JToggleButton jToggleButton_Sinif;
    // End of variables declaration//GEN-END:variables
}
